services:
  - type: web
    name: cardio-prediction-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r summative/API/requirements.txt
    startCommand: cd summative/API && python app.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PORT
        value: 8000
